version: '3'
services:
  hardhat:
    build: .
    volumes: 
      - ./hardhat:/app
      - /app/node_modules
      - ./contracts:/app/tmp/contracts
    ports:
      - 8545:8545
  nest:
    build: .
    volumes:
      - .:/nest
    ports:
      - 3001:3000
    tty: true
    command: npm run start
    